name: RSS Feeds

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 1

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: "Blog"
        uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://jakub.jankiewicz.org/blog/rss.xml
          readme-section: main
      - name: "My Other Writings"
        uses: JasonEtco/rss-to-readme@v1
        with:
           feed-url: https://jakub.jankiewicz.org/rss.xml
           readme-section: other
