name: RSS Feeds

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: "Blog"
        uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://jakub.jankiewicz.org/blog/rss.xml
          readme-section: main

      - name: "WikiZEIT"
        uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://jcubic.pl/wikizeit/feed.xml
          max: 10
          readme-section: wikizeit

      - name: "My Other Writings"
        uses: JasonEtco/rss-to-readme@v1
        with:
           feed-url: https://jakub.jankiewicz.org/rss.xml
           max: 10
           readme-section: other
